# Site settings
title: Tara Rebecca Art
email: tara.rebecca.art@gmail.com
author: Tara Rebecca
description: Welcome to Tara Rebecca Art. Here you can buy personalised cartoons as a gift for a friend, relative or yourself. Digital or printed copies available.
baseurl: "/"
url: "tararebeccaart.com" # the base hostname & protocol for your site

facebook_username: tararebeccaart
instagram_username: tararebeccaart
etsy_username: TaraRebeccaArt

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-49751789-6

# SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
