# Site settings
title: Tara Rebecca Art
email: tararebeccasimmons@gmail.com
url: http://tararebeccaart.com
description: "Personalised cartoons"
baserul: 'http://tararebeccaart.com'

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#63a4c7'
  primary-light: '#75b4bf'
  links: '#ffffff'

# Footer settings
footer: Tara Rebecca Art

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/tararebecca_art
#  - title: email
#    url: mailto:tararebeccasimmons@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
