# Site settings
title: Tara Rebecca Art
email: tararebeccasimmons@gmail.com
url: http://tararebeccaart.com
description: "[To Edit] This is an example of a description for Tara Rebecca Art."
baserul: 'http://tararebeccaart.com'

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/tararebecca_art
#  - title: email
#    url: mailto:tararebeccasimmons@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
